# reconcile: kind=brew pattern="zsh-"
# reconcile: kind=cask pattern="^(cask:)?(font-|iterm2)"

brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "iterm2"
